services:
  backend:
    image: laurejanin/greenquest-backend:latest
    environment:
      - DB_USERNAME="username"
      - DB_PASSWORD="password"
      - DB_DATABASE="dbname"
      - DB_HOST="database"
      - JWT_SECRET="secret"
  database:
    image: postgres
    # restart: always
    # ports:
    #   - 5433:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER="username"
      - POSTGRES_PASSWORD="password"
      - POSTGRES_DB="dbname"
  frontend:
    image: laurejanin/greenquest-frontend:latest
  nginx:
    stop_grace_period: 0s
    image: nginx:1.21.3
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./logs:/var/log/nginx
