services:
  backend:
    build: ./backend
    ports:
      - 5050:5050
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src/:/app/src/
      - ./backend/public/uploads:/app/backend/public/uploads

  database:
    image: postgres
    # restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src/:/app/src/
      - ./frontend/public/:/app/public/
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_BACK_URL=http://localhost:5050
    command: npm run dev
