name: Notify Slack on Workflow Failure

on:
  workflow_run:
    types:
      - completed

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Get workflow and job information
        id: extract_info
        run: |
          echo "::set-output name=workflow::${{ github.event.workflow.name }}"
          echo "::set-output name=job::${{ github.event.workflow_run.name }}"
      - name: Send Slack notification on failure
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: "Le job '${{ steps.extract_info.outputs.job }}' dans le workflow '${{ steps.extract_info.outputs.workflow }}' a échoué."
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
